development: &common
  adapter: postgresql
  encoding: unicode
  database: saan_tayo_development
  host: localhost
  pool: 5
  username: adillera
  password: 123qwe

test:
  <<: *common
  database: saan_tayo_test

production:
  <<: *common
  database: saan_tayo_production
